CREATE TABLE IF NOT EXISTS `shorten_urls` (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  original_url TEXT NOT NULL,
  short_code VARCHAR(255) NOT NULL UNIQUE,
  clicks INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);